# Default values for speedtest2influx.
# This is a YAML-formatted file.

image:
  repository: adamthesax/speedtest2influx 
  pullPolicy: IfNotPresent
  tag: ""

speedtest:
  interval: "300"
  server: ""
influxdb:
  url: ""
  token: ""
  org: ""
  bucket: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
